import React, { useState, useMemo } from "react";
import PageHeader from "@/components/PageHeader";
import { BILLS_FOR_HR } from "@/lib/mock";
import {
  FileText, Download, CheckCircle2, AlertCircle, Hourglass,
  Filter, Search, MessageSquare, Banknote, TrendingUp, XCircle
} from "lucide-react";

const STATUS = {
  APPROVED:  { cls: "chip-emerald", icon: CheckCircle2, color: "var(--emerald)" },
  SUBMITTED: { cls: "chip-amber",   icon: Hourglass,    color: "#8a6018" },
  REJECTED:  { cls: "chip-rust",    icon: XCircle,      color: "var(--rust)" },
};

export default function HrBilling() {
  const [filter, setFilter] = useState("ALL");
  const [q, setQ] = useState("");

  const filtered = useMemo(() => {
    return BILLS_FOR_HR.filter((b) => {
      if (filter !== "ALL" && b.status !== filter) return false;
      if (q && !b.canteen.toLowerCase().includes(q.toLowerCase()) && !String(b.id).includes(q)) return false;
      return true;
    });
  }, [filter, q]);

  const total = BILLS_FOR_HR.length;
  const pending = BILLS_FOR_HR
    .filter((b) => b.status === "SUBMITTED")
    .reduce((a, b) => a + b.total, 0);
  const approved = BILLS_FOR_HR
    .filter((b) => b.status === "APPROVED")
    .reduce((a, b) => a + b.total, 0);

  return (
    <>
      <PageHeader
        eyebrow="Chapter X · Treasury · HR"
        title="Project monthly billing,"
        italicTail="reviewed with care"
        description="Bills are generated by Canteen Admins. As HR, you review, accept, and archive PDFs. Associated Project · 05 (CHQ)."
        right={
          <div className="chip chip-emerald" data-testid="audit-chip">
            <FileText size={13} />
            <span>FY 2026 · HR Desk</span>
          </div>
        }
      />

      {/* KPI strip */}
      <div className="grid md:grid-cols-3 gap-4 mb-8">
        <div className="atelier p-6 lift" data-testid="kpi-total">
          <div className="flex items-center justify-between">
            <div className="eyebrow">Total consolidated bills</div>
            <div className="grid place-items-center rounded-[10px]"
              style={{ width: 36, height: 36, background: "var(--emerald-soft)", color: "var(--emerald)" }}>
              <FileText size={16} />
            </div>
          </div>
          <div className="font-display tnum mt-5" style={{ fontSize: 56, fontWeight: 400, lineHeight: 1, letterSpacing: "-0.04em" }}>
            {total}
          </div>
          <div className="text-[12px] mt-2" style={{ color: "var(--ink-muted)" }}>
            across {new Set(BILLS_FOR_HR.map((b) => b.canteen)).size} canteens
          </div>
        </div>

        <div
          className="p-6 lift"
          style={{
            background: "linear-gradient(180deg, rgba(251,234,203,.65), rgba(245,231,196,.45))",
            border: "1px solid rgba(176,122,22,.28)",
            borderRadius: 14,
          }}
          data-testid="kpi-pending"
        >
          <div className="flex items-center justify-between">
            <div className="eyebrow" style={{ color: "#8a6018" }}>Total pending amount</div>
            <div className="grid place-items-center rounded-[10px]"
              style={{ width: 36, height: 36, background: "rgba(176,122,22,.18)", color: "#8a6018" }}>
              <Hourglass size={16} />
            </div>
          </div>
          <div className="font-display tnum mt-5" style={{ fontSize: 56, fontWeight: 400, lineHeight: 1, letterSpacing: "-0.04em", color: "#6a4a0e" }}>
            ₹{pending.toLocaleString("en-IN")}
          </div>
          <div className="text-[12px] mt-2" style={{ color: "#8a6018" }}>
            {BILLS_FOR_HR.filter((b) => b.status === "SUBMITTED").length} bills awaiting your nod
          </div>
        </div>

        <div
          className="p-6 lift"
          style={{
            background: "linear-gradient(135deg, var(--navy-2), var(--navy))",
            color: "var(--on-dark)",
            border: "1px solid rgba(84,189,245,.22)",
            borderRadius: 14,
          }}
          data-testid="kpi-approved"
        >
          <div className="flex items-center justify-between">
            <div className="eyebrow" style={{ color: "var(--on-dark-accent)" }}>Approved · settled</div>
            <div className="grid place-items-center rounded-[10px]"
              style={{ width: 36, height: 36, background: "rgba(84,189,245,.15)", color: "var(--on-dark-accent)" }}>
              <TrendingUp size={16} />
            </div>
          </div>
          <div className="font-display tnum mt-5" style={{ fontSize: 56, fontWeight: 400, lineHeight: 1, letterSpacing: "-0.04em" }}>
            <span style={{ color: "var(--on-dark-accent)", fontSize: 32 }}>₹</span>
            {approved.toLocaleString("en-IN")}
          </div>
          <div className="text-[12px] mt-2" style={{ color: "var(--on-dark-muted)" }}>
            cleared this fiscal window
          </div>
        </div>
      </div>

      {/* Filter strip */}
      <div className="atelier p-4 mb-6 flex flex-wrap items-center justify-between gap-3" data-testid="filter-strip">
        <div className="flex items-center gap-2">
          <Filter size={14} style={{ color: "var(--ink-muted)" }} />
          {["ALL", "SUBMITTED", "APPROVED", "REJECTED"].map((s) => (
            <button
              key={s}
              onClick={() => setFilter(s)}
              data-active={filter === s}
              data-testid={`filter-${s.toLowerCase()}`}
              className="px-3.5 py-1.5 rounded-full text-[11.5px] font-medium transition-all"
              style={{
                background: filter === s ? "var(--ink)" : "transparent",
                color: filter === s ? "var(--paper)" : "var(--ink-muted)",
                border: filter === s ? "1px solid var(--ink)" : "1px solid transparent",
                letterSpacing: "0.04em",
              }}
            >
              {s}
            </button>
          ))}
        </div>
        <div className="relative">
          <Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2" style={{ color: "var(--ink-muted)" }} />
          <input
            placeholder="Search by Bill # or canteen…"
            value={q}
            onChange={(e) => setQ(e.target.value)}
            data-testid="bill-search"
            className="input-atelier pl-9 min-w-[280px] text-[13px]"
          />
        </div>
      </div>

      {/* Table */}
      <div className="atelier overflow-hidden" data-testid="bills-table">
        <div className="p-5 flex items-center justify-between" style={{ borderBottom: "1px solid var(--hairline)" }}>
          <div>
            <div className="eyebrow">Canteen-generated bills</div>
            <div className="font-display text-[20px] mt-0.5" style={{ fontWeight: 500 }}>
              {filtered.length} {filtered.length === 1 ? "invoice" : "invoices"} in scope
            </div>
          </div>
          <button className="btn-ghost flex items-center gap-2 text-[12px]" data-testid="export-all">
            <Download size={13} />
            Export Ledger
          </button>
        </div>

        <table className="atelier-table">
          <thead>
            <tr>
              <th>Bill</th>
              <th>Canteen</th>
              <th>Month</th>
              <th>Coupons</th>
              <th>Rate</th>
              <th>Total</th>
              <th>Status</th>
              <th>Comments</th>
              <th style={{ textAlign: "right" }}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((b) => {
              const s = STATUS[b.status];
              const Icon = s.icon;
              return (
                <tr key={b.id} data-testid={`bill-${b.id}`}>
                  <td>
                    <span className="font-display italic" style={{ color: "var(--brass)", fontSize: 14 }}>№</span>
                    <span className="font-mono-tab ml-1.5">{String(b.id).padStart(4, "0")}</span>
                  </td>
                  <td className="text-[13.5px]">{b.canteen}</td>
                  <td className="font-mono-tab text-[12.5px]" style={{ color: "var(--ink-muted)" }}>{b.month}</td>
                  <td>
                    <span className="chip chip-emerald" style={{ padding: "4px 10px", fontSize: 12 }}>
                      {b.coupons}
                    </span>
                  </td>
                  <td className="font-mono-tab text-[13px]" style={{ color: "var(--ink-muted)" }}>₹{b.rate}</td>
                  <td>
                    <span className="font-display tnum" style={{ fontSize: 18, fontWeight: 500 }}>
                      ₹{b.total.toLocaleString("en-IN")}
                    </span>
                  </td>
                  <td>
                    <span className={`chip ${s.cls}`}>
                      <Icon size={11} />
                      {b.status}
                    </span>
                  </td>
                  <td className="text-[12.5px]" style={{ color: b.comments === "—" ? "var(--ink-faint)" : "var(--ink-2)" }}>
                    {b.comments === "—" ? (
                      <span className="font-mono-tab">—</span>
                    ) : (
                      <span className="flex items-center gap-1.5">
                        <MessageSquare size={11} style={{ color: "var(--brass)" }} />
                        {b.comments}
                      </span>
                    )}
                  </td>
                  <td style={{ textAlign: "right" }}>
                    <div className="flex items-center gap-2 justify-end">
                      {b.status === "APPROVED" && (
                        <button
                          className="btn-brass flex items-center gap-1.5 text-[11px] px-3 py-1.5"
                          data-testid={`pdf-${b.id}`}
                        >
                          <Download size={11} />
                          PDF
                        </button>
                      )}
                      {b.status === "SUBMITTED" && (
                        <>
                          <button
                            className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[11.5px] font-medium"
                            style={{
                              background: "var(--emerald)",
                              color: "var(--paper)",
                              border: "1px solid var(--emerald-2)",
                            }}
                            data-testid={`accept-${b.id}`}
                          >
                            <CheckCircle2 size={11} />
                            Accept
                          </button>
                          <button
                            className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[11.5px] font-medium"
                            style={{
                              background: "var(--spark)",
                              color: "#fff",
                              border: "1px solid rgba(226,58,48,.7)",
                            }}
                            data-testid={`review-${b.id}`}
                          >
                            <AlertCircle size={11} />
                            Review
                          </button>
                        </>
                      )}
                      {b.status === "REJECTED" && (
                        <span className="text-[12px] italic font-display" style={{ color: "var(--rust)" }}>
                          returned for revision
                        </span>
                      )}
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </>
  );
}
