// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbPGdN5z9X5JUy77V_pIM_ep27JwJX8HU',
    appId: '1:110044757938:web:2285b6eca16841f77baeab',
    messagingSenderId: '110044757938',
    projectId: 'lunch-app-e2b56',
    authDomain: 'lunch-app-e2b56.firebaseapp.com',
    storageBucket: 'lunch-app-e2b56.firebasestorage.app',
    measurementId: 'G-1FJTBE8ECH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN-8iTwB_c5AGQFqdI6JoBFHPRY0Q-wa0',
    appId: '1:110044757938:android:acd4632cd68987927baeab',
    messagingSenderId: '110044757938',
    projectId: 'lunch-app-e2b56',
    storageBucket: 'lunch-app-e2b56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQzr1dBHHq7M0eosXGqv5RbijWaLu6db8',
    appId: '1:110044757938:ios:430b75069f77fd2a7baeab',
    messagingSenderId: '110044757938',
    projectId: 'lunch-app-e2b56',
    storageBucket: 'lunch-app-e2b56.firebasestorage.app',
    androidClientId: '110044757938-acp3lsfgtot4fdv25mrop18i20p47oq3.apps.googleusercontent.com',
    iosClientId: '110044757938-9o6tabg4tc6kvn9setc37jb6j6s1q6rh.apps.googleusercontent.com',
    iosBundleId: 'com.example.lunchi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQzr1dBHHq7M0eosXGqv5RbijWaLu6db8',
    appId: '1:110044757938:ios:430b75069f77fd2a7baeab',
    messagingSenderId: '110044757938',
    projectId: 'lunch-app-e2b56',
    storageBucket: 'lunch-app-e2b56.firebasestorage.app',
    androidClientId: '110044757938-acp3lsfgtot4fdv25mrop18i20p47oq3.apps.googleusercontent.com',
    iosClientId: '110044757938-9o6tabg4tc6kvn9setc37jb6j6s1q6rh.apps.googleusercontent.com',
    iosBundleId: 'com.example.lunchi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbPGdN5z9X5JUy77V_pIM_ep27JwJX8HU',
    appId: '1:110044757938:web:491bca1308ee1b6e7baeab',
    messagingSenderId: '110044757938',
    projectId: 'lunch-app-e2b56',
    authDomain: 'lunch-app-e2b56.firebaseapp.com',
    storageBucket: 'lunch-app-e2b56.firebasestorage.app',
    measurementId: 'G-J8Q8W3BTE7',
  );
}
