name: lunchi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  http: ^1.6.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.2

  mobile_scanner: ^4.0.1
  pretty_qr_code: ^3.0.0

  cupertino_icons: ^1.0.8
  uuid: ^4.2.2
  audioplayers: ^6.4.0
  share_plus: ^10.1.2
  path_provider: ^2.1.4
  flutter_secure_storage: ^10.3.1
  flutter_jailbreak_detection: ^1.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # ✅ Match Flutter 3.22+ lints
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/lunchify_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    # Demo branded assets
    - assets/images/lunchify_logo.png
    - assets/images/sjvn_scene.png
    - assets/images/sjvn_bg.png
    - assets/images/food_tray_bg.png
    - assets/images/splashscreen.png
    - assets/images/floating_icons_1.png
    - assets/images/floating_icons_2.png
    - assets/images/logo.png
    - assets/images/w_logo.png
    - assets/audio/applepay.mp3

  fonts:
    - family: FKGrotesk
      fonts:
        - asset: assets/fonts/FKGrotesk/FKGroteskTrial-Regular.otf
        - asset: assets/fonts/FKGrotesk/FKGroteskTrial-Medium.otf
          weight: 500
        - asset: assets/fonts/FKGrotesk/FKGroteskTrial-Bold.otf
          weight: 700
        - asset: assets/fonts/FKGrotesk/FKGroteskTrial-Italic.otf
          style: italic
        - asset: assets/fonts/FKGrotesk/FKGroteskTrial-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/FKGrotesk/FKGroteskTrial-BoldItalic.otf
          weight: 700
          style: italic
    - family: EBGaramond
      fonts:
        - asset: assets/fonts/EBGaramond/EBGaramond-VariableFont_wght.ttf
        - asset: assets/fonts/EBGaramond/EBGaramond-Italic-VariableFont_wght.ttf
          style: italic
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-ExtraBold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Playfair_Display/Roboto-VariableFont_wdth,wght.ttf
    - family: Typewriter
      fonts:
        - asset: assets/fonts/AmericanTypewriter/ufonts.com_american-typewriter.ttf

        - asset: assets/fonts/AmericanTypewriter/ufonts.com_american-typewriter-light.ttf
          weight: 300

dependency_overrides:
  path_provider_android: ^2.2.14