const express = require("express");
const router = express.Router();
const { mysqlPool } = require("../db");
const { requireAuth, requireHRAdmin } = require("../middleware/auth.middleware");
const PDFDocument = require("pdfkit");
const fs = require("fs");

// Require authentication for all billing routes
router.use(requireAuth);

/**
 * 1. POST /api/billing/generate-canteen-bill
 * Generates a consolidated monthly bill for a given canteen.
 * Accessed by Canteen Admin from Flutter App.
 */
router.post("/generate-canteen-bill", async (req, res) => {
  const { bill_month, total_coupons_scanned, coupon_price, total_amount, place_generated } = req.body;
  const user = req.user;

  if (user.role !== 'canteen_admin') {
    return res.status(403).json({ error: "Only Canteen Admin can generate canteen bills" });
  }

  if (!bill_month || !total_coupons_scanned || !coupon_price || !total_amount) {
    return res.status(400).json({ error: "Missing required fields" });
  }

  try {
    // Delete existing bill if any to recreate (prevent duplicates for same month & canteen)
    await mysqlPool.query(
      "DELETE FROM monthly_bills WHERE canteen_id = ? AND bill_month = ?",
      [user.canteen_id, bill_month]
    );

    // Insert new monthly bill
    const [result] = await mysqlPool.query(
      `INSERT INTO monthly_bills 
       (employee_id, canteen_id, project_id, bill_month, total_coupons_used, coupon_price, total_amount, status, place_generated) 
       VALUES (?, ?, ?, ?, ?, ?, ?, 'submitted', ?)`,
      [null, user.canteen_id, user.project_id, bill_month, total_coupons_scanned, coupon_price, total_amount, place_generated || 'Canteen Portal']
    );

    res.json({
      success: true,
      message: "Canteen Monthly bill generated successfully.",
      bill: {
        id: result.insertId,
        canteen_id: user.canteen_id,
        project_id: user.project_id,
        bill_month,
        total_coupons_used: total_coupons_scanned,
        coupon_price,
        total_amount,
        status: 'submitted',
        place_generated: place_generated || 'Canteen Portal',
        generated_at: new Date()
      }
    });
  } catch (err) {
    console.error("❌ Error generating canteen monthly bill:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * 1.5 GET /api/billing/canteen-bills
 * Retrieve all bills generated by the logged-in canteen
 */
router.get("/canteen-bills", async (req, res) => {
  const user = req.user;
  if (user.role !== 'canteen_admin') {
    return res.status(403).json({ error: "Only Canteen Admin can access this route" });
  }

  try {
    const [rows] = await mysqlPool.query(
      `SELECT * FROM monthly_bills WHERE canteen_id = ? ORDER BY generated_at DESC`,
      [user.canteen_id]
    );
    res.json(rows);
  } catch (err) {
    console.error("❌ Error fetching canteen bills:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * 2. GET /api/billing/project-bills
 * Retrieve all generated canteen bills for HR Admin's project or all if IT Admin
 */
router.get("/project-bills", requireHRAdmin, async (req, res) => {
  let projectId = req.user.project_id;
  
  if (req.user.role === 'it_admin' && req.query.project_id) {
    projectId = req.query.project_id;
  }

  try {
    let query = `
      SELECT b.*, c.name as canteen_name, p.name as project_name
      FROM monthly_bills b
      JOIN canteens c ON b.canteen_id = c.id
      JOIN projects p ON b.project_id = p.id
    `;
    const params = [];

    if (req.user.role === 'hr_admin' || (req.user.role === 'it_admin' && projectId)) {
      query += " WHERE b.project_id = ?";
      params.push(projectId);
    }

    query += " ORDER BY b.generated_at DESC";

    const [rows] = await mysqlPool.query(query, params);
    res.json(rows);
  } catch (err) {
    console.error("❌ Error fetching monthly bills:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * 3. PATCH /api/billing/:id/status
 * HR Admin approves or rejects the generated monthly bill
 */
router.patch("/:id/status", requireHRAdmin, async (req, res) => {
  const billId = req.params.id;
  const { status, comments } = req.body; // 'approved' or 'rejected' or 'review'

  if (!['approved', 'rejected', 'review'].includes(status)) {
    return res.status(400).json({ error: "Invalid status. Use approved, rejected, or review." });
  }

  try {
    // Verify the bill exists and belongs to the HR Admin's project
    const [billRows] = await mysqlPool.query(
      "SELECT project_id FROM monthly_bills WHERE id = ?",
      [billId]
    );

    if (billRows.length === 0) {
      return res.status(404).json({ error: "Bill not found" });
    }

    const bill = billRows[0];
    if (req.user.role === 'hr_admin' && bill.project_id !== req.user.project_id) {
      return res.status(403).json({ error: "Access denied. Bill belongs to another project." });
    }

    await mysqlPool.query(
      "UPDATE monthly_bills SET status = ?, comments = ? WHERE id = ?",
      [status, comments || null, billId]
    );

    res.json({ success: true, message: `Monthly bill status updated to ${status}` });
  } catch (err) {
    console.error("❌ Error updating bill status:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * 3.5 GET /api/billing/fruit-lunch-pdf
 * Canteen Admin downloads the PDF for fruit lunch orders of the current month
 */
router.get("/fruit-lunch-pdf", async (req, res) => {
  if (req.user.role !== 'canteen_admin') {
    return res.status(403).json({ error: "Only Canteen Admin can access this" });
  }

  try {
    const today = new Date();
    const monthStr = today.toLocaleDateString('en-CA').slice(0, 7); // YYYY-MM
    
    // Get all fruit lunch orders for this canteen in current month
    const [orders] = await mysqlPool.query(
      `SELECT o.*, u.name as employee_name, u.id as emp_id 
       FROM fruit_lunch_orders o
       JOIN users u ON o.employee_id = u.id
       WHERE o.canteen_id = ? 
       AND o.date LIKE ?
       ORDER BY o.date DESC, o.created_at DESC`,
      [req.user.canteen_id, `${monthStr}%`]
    );

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    res.setHeader('Content-disposition', `attachment; filename=Fruit_Lunch_Orders_${monthStr}.pdf`);
    res.setHeader('Content-type', 'application/pdf');
    doc.pipe(res);

    // --- Header ---
    doc.rect(0, 0, 600, 100).fill('#f4f8fc');
    doc.moveTo(0, 100).lineTo(600, 100).strokeColor('#c0d6f2').lineWidth(2).stroke();
    
    doc.font('Helvetica-Bold').fontSize(24).fillColor('#1a365d').text('SJVN Lunchify', 50, 25);
    doc.font('Helvetica-Bold').fontSize(16).fillColor('#1e3a8a').text(`Fruit Lunch Orders - ${monthStr}`, 50, 60);

    // --- Table Header ---
    const startY = 130;
    doc.font('Helvetica-Bold').fontSize(10).fillColor('#000');
    doc.text('Date', 50, startY);
    doc.text('Employee Name', 150, startY);
    doc.text('Emp ID', 350, startY);
    doc.text('Item', 430, startY);
    doc.text('Qty', 530, startY);
    doc.moveTo(50, startY + 15).lineTo(550, startY + 15).strokeColor('#ccc').lineWidth(1).stroke();

    // --- Table Rows ---
    let y = startY + 25;
    doc.font('Helvetica').fontSize(9).fillColor('#333');
    for (let i = 0; i < orders.length; i++) {
      if (y > 750) {
        doc.addPage();
        y = 50;
      }
      const o = orders[i];
      doc.text(o.date, 50, y);
      doc.text(o.employee_name, 150, y);
      doc.text(o.emp_id, 350, y);
      doc.text(o.name || '-', 430, y);
      doc.text(o.quantity.toString(), 530, y);
      
      doc.moveTo(50, y + 15).lineTo(550, y + 15).strokeColor('#eee').lineWidth(1).stroke();
      y += 25;
    }

    if (orders.length === 0) {
      doc.font('Helvetica-Oblique').text('No fruit lunch orders found for this month.', 50, y + 20);
    }

    doc.end();

  } catch (err) {
    console.error("❌ Error generating fruit lunch PDF:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * 4. GET /api/billing/:id/pdf
 * HR Admin downloads the PDF for an approved bill
 */
router.get("/:id/pdf", async (req, res) => {
  const billId = req.params.id;

  try {
    const [billRows] = await mysqlPool.query(
      `SELECT b.*, c.name as canteen_name, p.name as project_name 
       FROM monthly_bills b
       JOIN canteens c ON b.canteen_id = c.id
       JOIN projects p ON b.project_id = p.id
       WHERE b.id = ?`,
      [billId]
    );

    if (billRows.length === 0) {
      return res.status(404).json({ error: "Bill not found" });
    }

    const bill = billRows[0];

    // Access control
    if (req.user.role === 'hr_admin' && bill.project_id !== req.user.project_id) {
      return res.status(403).json({ error: "Access denied. Bill belongs to another project." });
    }
    if (req.user.role === 'canteen_admin' && bill.canteen_id !== req.user.canteen_id) {
      return res.status(403).json({ error: "Access denied. Bill belongs to another canteen." });
    }
    if (req.user.role === 'employee') {
      return res.status(403).json({ error: "Access denied." });
    }

    // Create a PDF document
    const doc = new PDFDocument({ margin: 0, size: 'A4' });
    res.setHeader('Content-disposition', `attachment; filename=Bill_${bill.bill_month}_${bill.canteen_name.replace(/\s+/g, '_')}.pdf`);
    res.setHeader('Content-type', 'application/pdf');
    doc.pipe(res);

    // Helper functions
    const drawLine = (x, y, length) => {
      doc.moveTo(x, y).lineTo(x + length, y).strokeColor('#e2e8f0').lineWidth(1).stroke();
    };

    // --- Header Background ---
    doc.rect(0, 0, 600, 150).fill('#f4f8fc');
    doc.moveTo(0, 150).lineTo(600, 150).strokeColor('#c0d6f2').lineWidth(2).stroke();

    // --- Header Texts ---
    // SJVN Lunchify
    doc.font('Helvetica-Bold').fontSize(24).fillColor('#1a365d').text('SJVN Lunchify', 50, 40);
    doc.font('Helvetica').fontSize(10).fillColor('#4a5568').text('Healthy Meals, Happy Employees', 50, 70);

    // Large Title
    doc.font('Helvetica-Bold').fontSize(28).fillColor('#1e3a8a').text('Canteen Monthly Bill', 50, 180);
    doc.rect(50, 215, 60, 4).fill('#2563eb');
    doc.font('Helvetica').fontSize(11).fillColor('#64748b').text('Thank you for choosing SJVN Lunchify!', 50, 230);

    // --- Top Info Bar (Rounded Rect) ---
    doc.roundedRect(50, 270, 495, 80, 8).fillAndStroke('#ffffff', '#e2e8f0');
    
    const yTop = 295;
    
    // BILL ID
    doc.font('Helvetica').fontSize(9).fillColor('#64748b').text('BILL ID', 70, yTop);
    doc.font('Helvetica-Bold').fontSize(14).fillColor('#0f172a').text(`#${bill.id}`, 70, yTop + 15);
    
    // DATE GENERATED
    doc.font('Helvetica').fontSize(9).fillColor('#64748b').text('DATE GENERATED', 160, yTop);
    doc.font('Helvetica-Bold').fontSize(14).fillColor('#0f172a').text(new Date(bill.generated_at).toLocaleDateString(), 160, yTop + 15);
    
    // BILLING MONTH
    doc.font('Helvetica').fontSize(9).fillColor('#64748b').text('BILLING MONTH', 310, yTop);
    doc.font('Helvetica-Bold').fontSize(14).fillColor('#0f172a').text(bill.bill_month, 310, yTop + 15);
    
    // STATUS
    doc.font('Helvetica').fontSize(9).fillColor('#64748b').text('STATUS', 440, yTop);
    
    // Status Pill
    const statusText = bill.status.toUpperCase();
    const isApproved = statusText === 'APPROVED';
    const pillColor = isApproved ? '#dcfce7' : '#fef08a';
    const pillText = isApproved ? '#166534' : '#854d0e';
    
    doc.roundedRect(440, yTop + 12, 85, 20, 10).fill(pillColor);
    doc.font('Helvetica-Bold').fontSize(10).fillColor(pillText).text(statusText, 440, yTop + 18, { width: 85, align: 'center' });

    // --- Middle Section ---
    const yMid = 380;
    
    // Left Box (Details)
    doc.roundedRect(50, yMid, 250, 220, 8).fillAndStroke('#ffffff', '#e2e8f0');
    
    // Items in Left Box
    const leftX = 70;
    let currY = yMid + 25;
    
    const printLeftItem = (label, value) => {
      doc.font('Helvetica').fontSize(9).fillColor('#64748b').text(label, leftX, currY);
      doc.font('Helvetica-Bold').fontSize(11).fillColor('#0f172a').text(value, leftX, currY + 12);
      currY += 40;
      if (currY < yMid + 180) {
        drawLine(leftX, currY - 5, 210);
      }
    };
    
    printLeftItem('PROJECT', bill.project_name);
    printLeftItem('CANTEEN', bill.canteen_name);
    printLeftItem('TOTAL COUPONS SCANNED', bill.total_coupons_used.toString());
    printLeftItem('PRICE PER COUPON', `INR ${bill.coupon_price}`);

    // Right Box (Total Amount)
    doc.roundedRect(320, yMid, 225, 220, 8).fillAndStroke('#f8fafc', '#bfdbfe');
    
    doc.font('Helvetica-Bold').fontSize(14).fillColor('#1e40af').text('Final Bill Amount', 320, yMid + 50, { align: 'center', width: 225 });
    
    doc.moveTo(350, yMid + 80).lineTo(515, yMid + 80).dash(2, { space: 2 }).strokeColor('#93c5fd').stroke();
    doc.undash(); // Reset dash
    
    doc.font('Helvetica-Bold').fontSize(32).fillColor('#1d4ed8').text(`INR ${bill.total_amount}`, 320, yMid + 105, { align: 'center', width: 225 });

    doc.moveTo(350, yMid + 160).lineTo(515, yMid + 160).dash(2, { space: 2 }).strokeColor('#93c5fd').stroke();
    doc.undash();
    
    // HR Comments if present
    if (bill.comments) {
      doc.roundedRect(50, 620, 495, 60, 8).fillAndStroke('#fffbeb', '#fde68a');
      doc.font('Helvetica-Bold').fontSize(10).fillColor('#92400e').text('HR Comments:', 70, 635);
      doc.font('Helvetica').fontSize(10).fillColor('#92400e').text(bill.comments, 70, 650, { width: 450 });
    }

    // --- Footer ---
    doc.roundedRect(50, 720, 495, 60, 8).fillAndStroke('#f8fafc', '#e2e8f0');
    doc.font('Helvetica-Bold').fontSize(10).fillColor('#0f172a').text('This is a system generated bill. No signature required.', 70, 735);
    doc.font('Helvetica').fontSize(9).fillColor('#64748b').text('For any queries, please contact the SJVN Lunchify support team.', 70, 755);

    doc.end();

  } catch (err) {
    console.error("❌ Error generating PDF:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

module.exports = router;
