import React, { useEffect, useState } from "react";
import api from "../services/api";
import { CircularProgress } from "@mui/material";

import DescriptionIcon from '@mui/icons-material/Description';
import DownloadIcon from '@mui/icons-material/Download';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import ErrorOutlineIcon from '@mui/icons-material/ErrorOutline';
import HourglassEmptyIcon from '@mui/icons-material/HourglassEmpty';
import FilterListIcon from '@mui/icons-material/FilterList';
import SearchIcon from '@mui/icons-material/Search';
import ChatBubbleOutlineIcon from '@mui/icons-material/ChatBubbleOutline';
import TrendingUpIcon from '@mui/icons-material/TrendingUp';
import CloseIcon from '@mui/icons-material/Close';

import PageHeader from "../components/PageHeader";

import "../styles/billing.css";

export default function BillingPanel({ user = {} }) {
  const [bills, setBills] = useState([]);
  const [loading, setLoading] = useState(false);
  const [reviewComment, setReviewComment] = useState("");
  const [activeReviewId, setActiveReviewId] = useState(null);

  // Filter and Search states
  const [statusFilter, setStatusFilter] = useState("ALL");
  const [searchQuery, setSearchQuery] = useState("");

  const fetchProjectBills = async () => {
    setLoading(true);
    try {
      const res = await api.get("/billing/project-bills");
      setBills(res.data);
    } catch (err) {
      console.error("Error fetching project bills:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchProjectBills();
  }, []);

  const handleUpdateStatus = async (billId, status, comments = null) => {
    try {
      const res = await api.patch(`/billing/${billId}/status`,
        { status, comments }
      );

      if (res.data.success) {
        alert(`Bill successfully marked as ${status}!`);
        setActiveReviewId(null);
        setReviewComment("");
        fetchProjectBills();
      }
    } catch (err) {
      alert(err.response?.data?.error || "Failed to update bill status");
    }
  };

  const handleDownloadPDF = async (billId) => {
    try {
      const res = await api.get(`/billing/${billId}/pdf`, { responseType: 'blob' });
      const url = window.URL.createObjectURL(new Blob([res.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `Bill_${billId}.pdf`);
      document.body.appendChild(link);
      link.click();
    } catch (err) {
      alert("Failed to download PDF");
    }
  };

  // Derive dynamic stats
  const totalBillsCount = bills.length;
  const uniqueCanteensCount = new Set(bills.map(b => b.canteen_name)).size;
  
  const pendingAmount = bills.reduce((sum, b) => 
    b.status === "submitted" || b.status === "review" ? sum + parseFloat(b.total_amount) : sum, 0
  );
  const awaitingNodCount = bills.filter(b => b.status === "submitted" || b.status === "review").length;

  const approvedAmount = bills.reduce((sum, b) => 
    b.status === "approved" ? sum + parseFloat(b.total_amount) : sum, 0
  );

  // Filter logic
  const filteredBills = bills.filter(b => {
    const matchesStatus = statusFilter === "ALL" || b.status.toUpperCase() === statusFilter;
    const matchesSearch = b.canteen_name.toLowerCase().includes(searchQuery.toLowerCase()) || 
                          String(b.id).includes(searchQuery);
    return matchesStatus && matchesSearch;
  });

  const STATUS_MAPPING = {
    APPROVED:  { cls: "chip-emerald", icon: CheckCircleIcon, color: "var(--emerald)" },
    SUBMITTED: { cls: "chip-amber",   icon: HourglassEmptyIcon, color: "#8a6018" },
    REJECTED:  { cls: "chip-rust",    icon: CloseIcon,      color: "var(--rust)" },
  };

  return (
    <>
      <PageHeader
        eyebrow="Chapter X · Treasury · HR"
        title="Project monthly billing,"
        italicTail="reviewed with care"
        description={`Bills are generated by Canteen Admins. As HR, you review, accept, and archive PDFs. Associated Project · ${user.project_id || '05 (CHQ)'}.`}
        right={
          <div className="chip chip-emerald" data-testid="audit-chip">
            <DescriptionIcon style={{ fontSize: 13 }} />
            <span>FY 2026 · HR Desk</span>
          </div>
        }
      />

      {/* KPI strip */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '16px', marginBottom: '32px' }}>
        <div className="atelier lift" style={{ padding: '24px' }} data-testid="kpi-total">
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div className="eyebrow">Total consolidated bills</div>
            <div style={{ display: 'grid', placeItems: 'center', borderRadius: '10px', width: '36px', height: '36px', background: "var(--emerald-soft)", color: "var(--emerald)" }}>
              <DescriptionIcon style={{ fontSize: 16 }} />
            </div>
          </div>
          <div className="font-display tnum" style={{ marginTop: '20px', fontSize: '56px', fontWeight: 400, lineHeight: 1, letterSpacing: "-0.04em" }}>
            {totalBillsCount}
          </div>
          <div style={{ fontSize: '12px', marginTop: '8px', color: "var(--ink-muted)" }}>
            across {uniqueCanteensCount} canteens
          </div>
        </div>

        <div
          className="lift"
          style={{
            padding: '24px',
            background: "linear-gradient(180deg, rgba(251,234,203,.65), rgba(245,231,196,.45))",
            border: "1px solid rgba(176,122,22,.28)",
            borderRadius: '14px',
          }}
          data-testid="kpi-pending"
        >
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div className="eyebrow" style={{ color: "#8a6018" }}>Total pending amount</div>
            <div style={{ display: 'grid', placeItems: 'center', borderRadius: '10px', width: '36px', height: '36px', background: "rgba(176,122,22,.18)", color: "#8a6018" }}>
              <HourglassEmptyIcon style={{ fontSize: 16 }} />
            </div>
          </div>
          <div className="font-display tnum" style={{ marginTop: '20px', fontSize: '56px', fontWeight: 400, lineHeight: 1, letterSpacing: "-0.04em", color: "#6a4a0e" }}>
            ₹{pendingAmount.toLocaleString("en-IN", { maximumFractionDigits: 0 })}
          </div>
          <div style={{ fontSize: '12px', marginTop: '8px', color: "#8a6018" }}>
            {awaitingNodCount} bills awaiting your nod
          </div>
        </div>

        <div
          className="lift"
          style={{
            padding: '24px',
            background: "linear-gradient(135deg, var(--navy-2), var(--navy))",
            color: "var(--on-dark)",
            border: "1px solid rgba(84,189,245,.22)",
            borderRadius: '14px',
          }}
          data-testid="kpi-approved"
        >
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div className="eyebrow" style={{ color: "var(--on-dark-accent)" }}>Approved · settled</div>
            <div style={{ display: 'grid', placeItems: 'center', borderRadius: '10px', width: '36px', height: '36px', background: "rgba(84,189,245,.15)", color: "var(--on-dark-accent)" }}>
              <TrendingUpIcon style={{ fontSize: 16 }} />
            </div>
          </div>
          <div className="font-display tnum" style={{ marginTop: '20px', fontSize: '56px', fontWeight: 400, lineHeight: 1, letterSpacing: "-0.04em" }}>
            <span style={{ color: "var(--on-dark-accent)", fontSize: '32px' }}>₹</span>
            {approvedAmount.toLocaleString("en-IN", { maximumFractionDigits: 0 })}
          </div>
          <div style={{ fontSize: '12px', marginTop: '8px', color: "var(--on-dark-muted)" }}>
            cleared this fiscal window
          </div>
        </div>
      </div>

      {/* Filter strip */}
      <div className="atelier" style={{ padding: '16px', marginBottom: '24px', display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: '12px' }} data-testid="filter-strip">
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <FilterListIcon style={{ fontSize: 14, color: "var(--ink-muted)" }} />
          {["ALL", "SUBMITTED", "APPROVED", "REJECTED"].map((s) => (
            <button
              key={s}
              onClick={() => setStatusFilter(s)}
              data-active={statusFilter === s}
              data-testid={`filter-${s.toLowerCase()}`}
              style={{
                padding: '6px 14px',
                borderRadius: '9999px',
                fontSize: '11.5px',
                fontWeight: 500,
                transition: 'all 0.2s',
                background: statusFilter === s ? "var(--ink)" : "transparent",
                color: statusFilter === s ? "var(--paper)" : "var(--ink-muted)",
                border: statusFilter === s ? "1px solid var(--ink)" : "1px solid transparent",
                letterSpacing: "0.04em",
                cursor: 'pointer'
              }}
            >
              {s}
            </button>
          ))}
        </div>
        <div style={{ position: 'relative' }}>
          <SearchIcon style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', fontSize: 13, color: "var(--ink-muted)" }} />
          <input
            placeholder="Search by Bill # or canteen…"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            data-testid="bill-search"
            className="input-atelier"
            style={{ paddingLeft: '36px', minWidth: '280px', fontSize: '13px' }}
          />
        </div>
      </div>

      {/* Table */}
      <div className="atelier" style={{ overflow: 'hidden' }} data-testid="bills-table">
        <div style={{ padding: '20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: "1px solid var(--hairline)" }}>
          <div>
            <div className="eyebrow">Canteen-generated bills</div>
            <div className="font-display" style={{ fontSize: '20px', marginTop: '2px', fontWeight: 500 }}>
              {filteredBills.length} {filteredBills.length === 1 ? "invoice" : "invoices"} in scope
            </div>
          </div>
          <button className="btn-ghost" style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '12px' }} data-testid="export-all">
            <DownloadIcon style={{ fontSize: 13 }} />
            Export Ledger
          </button>
        </div>

        {loading ? (
          <div style={{ padding: '40px 0', textAlign: 'center' }}>
            <CircularProgress size={24} style={{ color: "var(--ink)", marginBottom: 12 }} />
            <p style={{ fontSize: 13, color: 'var(--ink-muted)' }}>Fetching project bills list...</p>
          </div>
        ) : filteredBills.length === 0 ? (
          <div style={{ padding: '40px 0', textAlign: 'center', color: 'var(--ink-muted)', fontSize: 13 }}>
            <p>No invoices match the active scope.</p>
          </div>
        ) : (
          <table className="atelier-table">
            <thead>
              <tr>
                <th style={{ textAlign: "left" }}>Bill</th>
                <th style={{ textAlign: "left" }}>Canteen</th>
                <th style={{ textAlign: "left" }}>Month</th>
                <th style={{ textAlign: "left" }}>Coupons</th>
                <th style={{ textAlign: "left" }}>Rate</th>
                <th style={{ textAlign: "left" }}>Total</th>
                <th style={{ textAlign: "left" }}>Status</th>
                <th style={{ textAlign: "left" }}>Comments</th>
                <th style={{ textAlign: "right" }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredBills.map((bill) => {
                const rawStatus = (bill.status || "").toUpperCase();
                const mappedStatus = rawStatus === "REVIEW" ? "SUBMITTED" : rawStatus;
                const s = STATUS_MAPPING[mappedStatus] || STATUS_MAPPING.SUBMITTED;
                const Icon = s.icon;
                
                const isSubmitted = mappedStatus === "SUBMITTED";
                const isApproved = mappedStatus === "APPROVED";
                const isRejected = mappedStatus === "REJECTED";

                return (
                  <tr key={bill.id} data-testid={`bill-${bill.id}`}>
                    <td>
                      <span className="font-display italic" style={{ color: "var(--brass)", fontSize: 14 }}>№</span>
                      <span className="font-mono-tab" style={{ marginLeft: '6px' }}>{String(bill.id).padStart(4, "0")}</span>
                    </td>
                    <td style={{ fontSize: '13.5px' }}>{bill.canteen_name}</td>
                    <td className="font-mono-tab" style={{ fontSize: '12.5px', color: "var(--ink-muted)" }}>{bill.bill_month}</td>
                    <td>
                      <span className="chip chip-emerald" style={{ padding: "4px 10px", fontSize: 12 }}>
                        {bill.total_coupons_used}
                      </span>
                    </td>
                    <td className="font-mono-tab" style={{ fontSize: '13px', color: "var(--ink-muted)" }}>₹{bill.coupon_price}</td>
                    <td>
                      <span className="font-display tnum" style={{ fontSize: 18, fontWeight: 500 }}>
                        ₹{parseFloat(bill.total_amount).toLocaleString("en-IN", { maximumFractionDigits: 0 })}
                      </span>
                    </td>
                    <td>
                      <span className={`chip ${s.cls}`}>
                        <Icon style={{ fontSize: 11 }} />
                        {rawStatus}
                      </span>
                    </td>
                    <td style={{ fontSize: '12.5px', color: bill.comments === "—" || !bill.comments ? "var(--ink-faint)" : "var(--ink-2)" }}>
                      {activeReviewId === bill.id ? (
                        <input 
                          type="text" 
                          className="input-atelier"
                          value={reviewComment} 
                          onChange={(e) => setReviewComment(e.target.value)} 
                          placeholder="Add comments..." 
                          style={{ width: '140px', padding: '4px 8px', fontSize: '12px' }}
                          aria-label="Add review comments"
                        />
                      ) : bill.comments === "—" || !bill.comments ? (
                        <span className="font-mono-tab">—</span>
                      ) : (
                        <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                          <ChatBubbleOutlineIcon style={{ fontSize: 11, color: "var(--brass)" }} />
                          {bill.comments}
                        </span>
                      )}
                    </td>
                    <td style={{ textAlign: "right" }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', justifyContent: 'flex-end' }}>
                        {isApproved && (
                          <button
                            className="btn-brass"
                            style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '11px', padding: '6px 12px' }}
                            data-testid={`pdf-${bill.id}`}
                            onClick={() => handleDownloadPDF(bill.id)}
                          >
                            <DownloadIcon style={{ fontSize: 11 }} />
                            PDF
                          </button>
                        )}
                        {isSubmitted && activeReviewId !== bill.id && (
                          <>
                            <button
                              style={{
                                display: 'flex', alignItems: 'center', gap: '6px', padding: '6px 12px', borderRadius: '9999px', fontSize: '11.5px', fontWeight: 500,
                                background: "var(--emerald)",
                                color: "var(--paper)",
                                border: "1px solid var(--emerald-2)",
                                cursor: 'pointer'
                              }}
                              data-testid={`accept-${bill.id}`}
                              onClick={() => handleUpdateStatus(bill.id, "approved")}
                            >
                              <CheckCircleIcon style={{ fontSize: 11 }} />
                              Accept
                            </button>
                            <button
                              style={{
                                display: 'flex', alignItems: 'center', gap: '6px', padding: '6px 12px', borderRadius: '9999px', fontSize: '11.5px', fontWeight: 500,
                                background: "var(--spark)",
                                color: "#fff",
                                border: "1px solid rgba(226,58,48,.7)",
                                cursor: 'pointer'
                              }}
                              data-testid={`review-${bill.id}`}
                              onClick={() => setActiveReviewId(bill.id)}
                            >
                              <ErrorOutlineIcon style={{ fontSize: 11 }} />
                              Review
                            </button>
                          </>
                        )}
                        {activeReviewId === bill.id && (
                          <div style={{ display: 'flex', gap: '6px' }}>
                            <button style={{ background: 'var(--rust)', borderRadius: '99px', padding: '6px 12px', fontSize: '11px', color: '#fff', border: 'none', cursor: 'pointer', fontWeight: 500 }} onClick={() => handleUpdateStatus(bill.id, "review", reviewComment)}>Submit</button>
                            <button style={{ background: 'transparent', borderRadius: '99px', padding: '6px 12px', fontSize: '11px', border: '1px solid var(--hairline-strong)', cursor: 'pointer', fontWeight: 500, color: 'var(--ink)' }} onClick={() => setActiveReviewId(null)}>Cancel</button>
                          </div>
                        )}
                        {isRejected && (
                          <span style={{ fontSize: '12px', fontStyle: 'italic', color: 'var(--rust)' }} className="font-display">
                            returned for revision
                          </span>
                        )}
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        )}
      </div>
    </>
  );
}
