import React, { useEffect, useState } from "react";
import axios from "axios";
import "../styles/billing.css";

export default function BillingPanel() {
  const token = localStorage.getItem("adminToken");
  const user = JSON.parse(localStorage.getItem("adminUser") || "{}");

  const [bills, setBills] = useState([]);
  const [loading, setLoading] = useState(false);
  const [reviewComment, setReviewComment] = useState("");
  const [activeReviewId, setActiveReviewId] = useState(null);

  const axiosConfig = {
    headers: { Authorization: `Bearer ${token}` }
  };

  const fetchProjectBills = async () => {
    setLoading(true);
    try {
      const res = await axios.get("http://localhost:3001/api/billing/project-bills", axiosConfig);
      setBills(res.data);
    } catch (err) {
      console.error("Error fetching project bills:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchProjectBills();
  }, []);

  const handleUpdateStatus = async (billId, status, comments = null) => {
    try {
      const res = await axios.patch(
        `http://localhost:3001/api/billing/${billId}/status`,
        { status, comments },
        axiosConfig
      );

      if (res.data.success) {
        alert(`Bill successfully marked as ${status}!`);
        setActiveReviewId(null);
        setReviewComment("");
        fetchProjectBills();
      }
    } catch (err) {
      alert(err.response?.data?.error || "Failed to update bill status");
    }
  };

  const handleDownloadPDF = async (billId) => {
    try {
      const res = await axios.get(`http://localhost:3001/api/billing/${billId}/pdf`, {
        ...axiosConfig,
        responseType: 'blob'
      });
      const url = window.URL.createObjectURL(new Blob([res.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `Bill_${billId}.pdf`);
      document.body.appendChild(link);
      link.click();
    } catch (err) {
      alert("Failed to download PDF");
    }
  };

  return (
    <div className="billing-panel-container fade-in">
      <div className="billing-header">
        <div>
          <h2>💳 Project Monthly Billing (HR Review)</h2>
          <p className="hr-project-tag">💼 Associated Project ID: {user.project_id}</p>
        </div>
      </div>

      <div className="billing-grid">
        {/* BILLS SUMMARY STATS */}
        <div className="billing-quick-stats" style={{ gridColumn: '1 / -1', display: 'flex', gap: '20px' }}>
          <div className="quick-stat-box count-box">
            <h4>Total Consolidated Bills</h4>
            <p>{bills.length}</p>
          </div>
          <div className="quick-stat-box amt-box">
            <h4>Total Pending Amount</h4>
            <p>₹ {bills.reduce((sum, b) => b.status === "submitted" || b.status === "review" ? sum + parseFloat(b.total_amount) : sum, 0).toFixed(2)}</p>
          </div>
        </div>
      </div>

      {/* BILLS LIST SECTION */}
      <div className="bills-list-section">
        <h3>📄 Canteen Generated Bills</h3>
        <p className="form-info" style={{marginBottom: "16px"}}>Bills are generated by Canteen Admins. HR can review, accept, and download PDFs.</p>

        {loading ? (
          <div className="bills-loading">
            <div className="spinner"></div>
            <p>Fetching project bills list...</p>
          </div>
        ) : bills.length === 0 ? (
          <div className="bills-empty">
            <p>📭 No monthly bills generated for your project canteens yet.</p>
          </div>
        ) : (
          <div className="bills-table-wrapper">
            <table className="bills-table">
              <thead>
                <tr>
                  <th>Bill ID</th>
                  <th>Canteen Name</th>
                  <th>Month</th>
                  <th>Coupons Scanned</th>
                  <th>Price/Coupon</th>
                  <th>Total Amount</th>
                  <th>Status</th>
                  <th>Comments</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {bills.map((bill) => (
                  <tr key={bill.id}>
                    <td>#{bill.id}</td>
                    <td><strong>{bill.canteen_name}</strong></td>
                    <td><span className="month-badge">{bill.bill_month}</span></td>
                    <td><span className="coupons-count">{bill.total_coupons_used}</span></td>
                    <td>₹{bill.coupon_price}</td>
                    <td><strong>₹ {bill.total_amount}</strong></td>
                    <td>
                      <span className={`status-badge bill-${bill.status}`}>
                        {bill.status.toUpperCase()}
                      </span>
                    </td>
                    <td>
                      {activeReviewId === bill.id ? (
                        <input 
                          type="text" 
                          value={reviewComment} 
                          onChange={(e) => setReviewComment(e.target.value)} 
                          placeholder="Add comments..." 
                          style={{width: '150px', padding: '4px'}}
                        />
                      ) : (
                        <span style={{fontSize: '12px', color: '#555'}}>{bill.comments || "-"}</span>
                      )}
                    </td>
                    <td>
                      <div className="action-buttons">
                        {(bill.status === "submitted" || bill.status === "review") && activeReviewId !== bill.id && (
                          <>
                            <button 
                              className="btn-action btn-approve"
                              onClick={() => handleUpdateStatus(bill.id, "approved")}
                            >
                              Accept
                            </button>
                            <button 
                              className="btn-action btn-reject"
                              onClick={() => setActiveReviewId(bill.id)}
                            >
                              Review
                            </button>
                          </>
                        )}
                        {activeReviewId === bill.id && (
                          <div style={{display: 'flex', gap: '4px'}}>
                             <button className="btn-action btn-reject" onClick={() => handleUpdateStatus(bill.id, "review", reviewComment)}>Submit Review</button>
                             <button className="btn-action" onClick={() => setActiveReviewId(null)}>Cancel</button>
                          </div>
                        )}
                        {bill.status === "approved" && (
                          <button 
                            className="btn-action" 
                            style={{background: '#0d6efd'}}
                            onClick={() => handleDownloadPDF(bill.id)}
                          >
                            PDF
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
